# Generated by Django 5.1.7 on 2025-04-02 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_alter_auction_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="rating",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=3,
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
