# Generated by Django 5.1.7 on 2025-05-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_alter_bid_bidder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="bidder",
            field=models.CharField(max_length=150),
        ),
    ]
