# Generated by Django 5.1.7 on 2025-04-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_bid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bid",
            old_name="amount",
            new_name="price",
        ),
        migrations.AlterField(
            model_name="bid",
            name="bidder",
            field=models.CharField(max_length=150),
        ),
    ]
